title: Cherri 🍒
description: iOS Siri Shortcuts Programming Language

theme: just-the-docs
logo: "/assets/cherri_light.png"
color_scheme: cherri
callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: purple
  important:
    title: Important
    color: red

aux_links:
  "GitHub":
    - "//github.com/electrikmilk/cherri"
aux_links_new_tab: true

nav_external_links:
  - title: Code Tour
    url: https://www.youtube.com/watch?v=gU8TsI96uww
    hide_icon: false
