title: Cherri 🍒
description: iOS Siri Shortcuts Programming Language

theme: just-the-docs
logo: "/assets/cherri.png"
color_scheme: cherri

aux_links:
  "GitHub":
    - "//github.com/electrikmilk/cherri"
aux_links_new_tab: true
