title: Cherri 🍒
description: iOS Siri Shortcuts Programming Language

theme: just-the-docs
logo: "/assets/cherri_light.png"
color_scheme: cherri
callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue
  important:
    title: Important
    color: red

aux_links:
  "View Source on GitHub":
    - "//github.com/electrikmilk/cherri"
aux_links_new_tab: true

nav_external_links:
  - title: Code Tour
    url: https://www.youtube.com/watch?v=gU8TsI96uww
    hide_icon: false

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust
markup / liquid-based content.
footer_content: "Copyright &copy; 2017-2020 Brandon Jordan. Distributed by an <a href=\"https://github.com/electrikmilk/cherri/blob/main/LICENSE\">GPL 2.0 License.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/electrikmilk/cherri" # the github URL for your repo
gh_edit_branch: "documentation" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "edit" # "tree" or "edit" if you want the user to jump into the editor immediately
